apiVersion: v1
kind: ServiceAccount
metadata:
  name: golden-path-demo
  namespace: golden-path-demo
  labels:
    app: golden-path-demo
    environment: dev
    managed-by: argocd
    app.kubernetes.io/name: golden-path-demo
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: golden-path-demo
  annotations:
    iam.amazonaws.com/role: "arn:aws:iam::123456789012:role/golden-path-demo-role"
automountServiceAccountToken: false