apiVersion: v1
kind: Service
metadata:
  name: {{appName}}
  namespace: default
  labels:
    app: {{appName}}
    version: v1
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: {{appName}}
    version: v1