apiVersion: v1
kind: Namespace
metadata:
  name: {{ namespace | default(appName) }}
  labels:
    app.kubernetes.io/name: {{ appName }}
    app.kubernetes.io/managed-by: golden-path-agent
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
