apiVersion: v1
kind: Service
metadata:
  name: {{appName}}
  labels:
    app: {{appName}}
spec:
  selector:
    app: {{appName}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP