apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: "{{ appName }}"
  app.kubernetes.io/managed-by: golden-path-agent
resources:
  - task-test.yaml
  - task-build.yaml
  - task-bump-gitops.yaml
  - pipeline.yaml
  - trigger.yaml
